config/routes.rb
Rails.application.routes.draw do
  resources :bits
  resources :users
  resources :inventions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "inventions#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bit.rb
class Bit < ApplicationRecord
  has_and_belongs_to_many :inventions
end

app/models/invention.rb
class Invention < ApplicationRecord
  has_and_belongs_to_many :bits
  has_one :user #, required: true

  accepts_nested_attributes_for :bits, :user, allow_destroy: true

  acts_as_taggable_on :other_materials

	validates :title, :presence => true, :length => { :maximum => 255 }
  validates :description, :presence => true, :length => { :maximum => 255 }
  validates :user_name, :length => { :maximum => 255 }
  validates :email_address, :length => { :maximum => 255 }

  #validate :must_have_a_bit

  #def must_have_a_bit
  #  if bit_ids.empty?
  #    errors.add(:base, 'Must have at least one Bit selected.')
  #  end
  #end
end

app/models/user.rb
class User < ApplicationRecord
  #belongs_to :invention
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bits_controller.rb
class BitsController < ApplicationController
  before_action :set_bit, only: [:show, :edit, :update, :destroy]

  # GET /bits
  # GET /bits.json
  def index
    @bits = Bit.all
  end

  # GET /bits/1
  # GET /bits/1.json
  def show
  end

  # GET /bits/new
  def new
    @bit = Bit.new
  end

  # GET /bits/1/edit
  def edit
  end

  # POST /bits
  # POST /bits.json
  def create
    @bit = Bit.new(bit_params)

    respond_to do |format|
      if @bit.save
        format.html { redirect_to @bit, notice: 'Bit was successfully created.' }
        format.json { render :show, status: :created, location: @bit }
      else
        format.html { render :new }
        format.json { render json: @bit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bits/1
  # PATCH/PUT /bits/1.json
  def update
    respond_to do |format|
      if @bit.update(bit_params)
        format.html { redirect_to @bit, notice: 'Bit was successfully updated.' }
        format.json { render :show, status: :ok, location: @bit }
      else
        format.html { render :edit }
        format.json { render json: @bit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bits/1
  # DELETE /bits/1.json
  def destroy
    @bit.destroy
    respond_to do |format|
      format.html { redirect_to bits_url, notice: 'Bit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bit
      @bit = Bit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bit_params
      params.require(:bit).permit(:name, :invention_id)
    end
end

app/controllers/inventions_controller.rb
class InventionsController < ApplicationController
  before_action :set_invention, only: [:show, :edit, :update, :destroy]

  # GET /inventions
  # GET /inventions.json
  def index
    @inventions = Invention.all
  end

  # GET /inventions/1
  # GET /inventions/1.json
  def show
  end

  # GET /inventions/new
  def new
    @invention = Invention.new
    #@invention.user.build
    #@invention.bits.build
  end

  # GET /inventions/1/edit
  def edit
  end

  # POST /inventions
  # POST /inventions.json
  def create
    @invention = Invention.new(invention_params)

    respond_to do |format|
      if @invention.save
        format.html { redirect_to @invention, notice: 'Invention was successfully created.' }
        format.json { render :show, status: :created, location: @invention }
      else
        format.html { render :new }
        format.json { render json: @invention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventions/1
  # PATCH/PUT /inventions/1.json
  def update
    respond_to do |format|
      if @invention.update(invention_params)
        format.html { redirect_to @invention, notice: 'Invention was successfully updated.' }
        format.json { render :show, status: :ok, location: @invention }
      else
        format.html { render :edit }
        format.json { render json: @invention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventions/1
  # DELETE /inventions/1.json
  def destroy
    @invention.destroy
    respond_to do |format|
      format.html { redirect_to inventions_url, notice: 'Invention was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invention
      @invention = Invention.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invention_params
      params.require(:invention).permit(:title, :description, :user_name, :email_address, :other_material_list, :user_attributes => [:user_name, :email_address, :invention_id, :_destroy], :bit_attributes => [:name, :_destroy])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :email_address, :invention_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bits_helper.rb
module BitsHelper
end

app/helpers/inventions_helper.rb
module InventionsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bits/_form.html.erb
<%= form_for(bit) do |f| %>
  <% if bit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bit.errors.count, "error") %> prohibited this bit from being saved:</h2>

      <ul>
      <% bit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :invention_id %>
    <%= f.text_field :invention_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bits/edit.html.erb
<h1>Editing Bit</h1>

<%= render 'form', bit: @bit %>

<%= link_to 'Show', @bit %> |
<%= link_to 'Back', bits_path %>

app/views/bits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Invention</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bits.each do |bit| %>
      <tr>
        <td><%= bit.name %></td>
        <td><%= bit.invention %></td>
        <td><%= link_to 'Show', bit %></td>
        <td><%= link_to 'Edit', edit_bit_path(bit) %></td>
        <td><%= link_to 'Destroy', bit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bit', new_bit_path %>

app/views/bits/new.html.erb
<h1>New Bit</h1>

<%= render 'form', bit: @bit %>

<%= link_to 'Back', bits_path %>

app/views/bits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bit.name %>
</p>

<p>
  <strong>Invention:</strong>
  <%= @bit.invention %>
</p>

<%= link_to 'Edit', edit_bit_path(@bit) %> |
<%= link_to 'Back', bits_path %>

app/views/inventions/_form.html.erb
<%= form_for(invention) do |f| %>
  <% if invention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invention.errors.count, "error") %> prohibited this invention from being saved:</h2>

      <ul>
      <% invention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  
  <div class="field">
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </div>

  <div class="field">
    <%= f.label :email_address %>
    <%= f.text_field :email_address %>
  </div>

  <div class="field">
    <%= collection_check_boxes(:invention, :bit_ids, Bit.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :other_material_list %>
    <small>Add any additional materials. Use a space between materials, and use a "-" for materials with spaces in their name.</small>
    <%= f.text_field :other_material_list, value: f.object.other_material_list.to_s %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventions/edit.html.erb
<h1>Editing Invention</h1>

<%= render 'form', invention: @invention %>

<%= link_to 'Show', @invention %> |
<%= link_to 'Back', inventions_path %>

app/views/inventions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventions.each do |invention| %>
      <tr>
        <td><%= link_to html_escape(invention.title), invention %></td>
        <td><%= h invention.description %></td>
        <td><%= link_to 'Show', invention %></td>
        <td><%= link_to 'Edit', edit_invention_path(invention) %></td>
        <td><%= link_to 'Destroy', invention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invention', new_invention_path %>

app/views/inventions/new.html.erb
<h1>New Invention</h1>

<%= render 'form', invention: @invention %>

<%= link_to 'Back', inventions_path %>

app/views/inventions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= h @invention.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= h @invention.description %>
</p>

<p>
  <strong>Username:</strong>
  <%= h @invention.user_name %>
</p>

<p>
  <strong>Email Address:</strong>
  <%= h @invention.email_address %>
</p>

<p>
  <strong>Bits Used:</strong>
  <% unless @invention.bits.empty? %>
    <ul>
      <% @invention.bits.each do |bit| %>
        <li><%= h bit.name %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<p>
  <strong>Other Materials:</strong>
  <% unless @invention.other_materials.empty? %>
    <ul>
      <% @invention.other_materials.each do |other_material| %>
        <li><%= h other_material.name %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<%= link_to 'Edit', edit_invention_path(@invention) %> |
<%= link_to 'Back', inventions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>littleKits</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </div>

  <div class="field">
    <%= f.label :email_address %>
    <%= f.text_field :email_address %>
  </div>

  <div class="field">
    <%= f.label :invention_id %>
    <%= f.text_field :invention_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Email address</th>
      <th>Invention</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_name %></td>
        <td><%= user.email_address %></td>
        <td><%= user.invention %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @user.user_name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @user.email_address %>
</p>

<p>
  <strong>Invention:</strong>
  <%= @user.invention %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>